### ISSUE TITLE
Tuple Index our of range on  normalized layer creation

### ISSUE THREAD

**Issue by knagrecha** [boyuanf/DeepQLearning#1]
Hello,

I was following through the tutorials that you list as sources when I noticed your comment and code, I attempted to run it to get a better understanding of what I needed to do. However, I am running into an issue, specifically that on line 84  

` normalized = layers.Lambda(lambda x: x / 255.0, name='normalization')(frames_input)`

there is an IndexError, tuple index out of range specifically. I know this is a rather old upload, but any help on this issue would be appreciated.

**Comment by boyuanf** [comment]
Hi,

As this is very first layer, I suggest you check if the frame read successfully, cool, saw you just close the issue.

**Comment by knagrecha** [comment]
I realized this is not an issue with the code, even when I shift the code many lines across the issue only appears in line 84.

**Comment by knagrecha** [comment]
Strangely, when I just hit enter a few times and moved it down several lines, leaving line 84 blank, it started to work. No idea what was happening there.
